[general]
import = [
  "~/.config/alacritty/themes/nord.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold   = { family = "FiraMono Nerd Font", style = "Bold" }

